name: Release

on:
  workflow_dispatch:
    inputs:
      version-string:
        description: 'Version (e.g. 0.8.3) or one of --major / --minor / --patch to bump from CHANGELOG.md'
        required: true
        default: --patch
        type: string

jobs:
  release:
    permissions:
      contents: write
    uses: Phantomical/KSPBuildTools/.github/workflows/create-release.yml@update-create-release
    with:
      version-string: ${{ inputs.version-string }}
      artifacts: GameData Extras LICENSE* README* CHANGELOG*
      flatten: true
      version-file: GameData/SystemHeat/Versioning/SystemHeat.version
